name: Update MAL Data
on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. Descargar repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js con Caché
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # Esta línea activa el caché automático de npm
          cache: 'npm'

      - name: 3. Instalar dependencias
        # 'npm ci' es más rápido y limpio que 'install' para entornos de CI/CD
        run: npm ci 

      - name: 4. Ejecutar Script
        run: node update_mal.js

      - name: 5. Guardar cambios
        run: |
          git config --global user.name 'MAL-Bot'
          git config --global user.email 'bot@github.com'
          git add assets/data/mal_data.json
          git commit -m "update: mal statistics (cached build)" || exit 0
          git push